project:
  type: website
  output-dir: docs

# Meta
description-meta: "Academic Website for Jack O'Brien"
author-meta: "Jack O'Brien"

website:
  title: ""
  image: ""
  description: "Academic Website for Jack O'Brien"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: About
            href: about.qmd
          - text: Contact
            href: contact.qmd             
      - text: Research
        menu: 
          - text: Student Research
            href: student.qmd
          - text: Research
            href: research.qmd
      - text: Teaching # Comment the Teaching part out to remove the Teaching page
        href: teaching.qmd
      - text: People   # Comment the Group part out to remove the Group page
        href: people.qmd

    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/cascobayesian
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Jack O'Brien](cascobayesian.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Built using the [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/cascobayesian
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/cascobayesian/
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://cascobayesian.github.io/"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

